# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./Source/aboutform.h \
    ./Source/mainwindow.h
SOURCES += ./Source/aboutform.cpp \
    ./Source/main.cpp \
    ./Source/mainwindow.cpp
FORMS += ./mainwindow.ui \
    ./aboutform.ui
RESOURCES += mainwindow.qrc
