name: build

on: [push, pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -y install build-essential cmake zlib1g-dev libgl1-mesa-dev libgl1-mesa-glx libusb-1.0-0-dev qt5-default
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
    - uses: actions/upload-artifact@v2
      with:
        name: build (linux)
        path: build

  win-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          make
          mingw-w64-x86_64
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-libusb
          mingw-w64-x86_64-qt5-static
    - name: Build
      shell: msys2 {0}
      run: |
        export PATH="/mingw64/bin:$PATH"
        mkdir build
        cd build
        cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DQt5Widgets_DIR=/d/a/_temp/msys/msys64/mingw64/qt5-static/lib/cmake/Qt5Widgets ..
        make
    - uses: actions/upload-artifact@v2
      with:
        name: build (windows)
        path: build

  macos-build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        shell: bash
        run: brew install libusb qt5 cmake

      - name: Build
        shell: bash
        run: mkdir build && cd build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DQt5Widgets_DIR=/usr/local/opt/qt5/lib/cmake/Qt5Widgets .. && make

      - uses: actions/upload-artifact@v2
        with:
          name: build (macos)
          path: build
