name: build

on: [push, pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -y install build-essential cmake zlib1g-dev libgl1-mesa-dev libgl1-mesa-glx libusb-1.0-0-dev qtbase5-dev

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
        cd ..
        cp ./Linux/README ./build/bin/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux
        path: ./build/bin/

  win-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          make
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-libusb
          mingw-w64-x86_64-qt5-base
          mingw-w64-x86_64-qt5-static
          mingw-w64-x86_64-qt5-tools          

    - name: Build
      shell: msys2 {0}
      run: |
        export PATH="/mingw64/bin:$PATH"
        mkdir build
        cd build
        cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release ..
        make
        windeployqt.exe heimdall-frontend.exe
        cd ..
        mkdir ./build/bin/Drivers/
        cp ./Win32/README.txt ./build/bin/
        cp ./Win32/Drivers/zadig.exe ./build/bin/Drivers/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: ./build/bin/
